name    'aggressivex-php'
version '1.0.0'
author  'Luis M. Hdez'
license 'MIT'
project_page 'http://opensource.aggressivex.com/puppet/php'
source  'https://github.com/aggressivex/puppet-php'
summary 'Puppet php setup'
description 'This module installs and sets up php.'